name: env_capes_teses
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pandas
  - numpy
  - jupyterlab
  - plotly
  - streamlit
  - seaborn
  - matplotlib
  - openpyxl
  - dask
  
